### ISSUE TITLE
Change JavaScript client to fire partial Submission on event

### ISSUE THREAD

**Issue by PeterMarinov** [endatix/endatix#237]
### Details
* Logic should be in separate JS file(s), so it can be used as a package in the future
* Following events will be used:
   - onComplete
   - onValueChanged
   - onDynamicPanelItemValueChanged
   - onMatrixCellValueChanged
   - onCurrentPageChanged

### Scope

- [x] Add JavaScript logic to execute the Submission logic based of the events from the spec
- [x] Add ability to execute the API request in queue (avoid concurrent calls)
- [x] Ensure Submit form clears the queue and executes immediately
- [ ] #267
- [x] Port the logic into the Endatix Hub app
- [ ] ~~Port the logic into the Corp Website submit logic (or similar)~~ `out-of-scope`
- [ ] ~~Create npm package~~ `out-of-scope`

### Acceptance Criteria

- Complete Submission is saved in the DB when the SurveyJS's `onComplete` event is fired
- During onComplete submission Submit button cannot be resubmitted twice
- Partial Submission is saved in the DB for the following SurveyJS's events -  `onValueChanged`, `onDynamicPanelItemValueChanged`, `onMatrixCellValueChanged`, `onCurrentPageChanged`
- Server side errors during partial submission should not break the UI of the form
- Create/Update Submission API calls should be executed one at a time

**Comment by PeterMarinov** [comment]
@orilux , @dspetrov  - looking at this task. The `onValueChanged` seems too frequent as it fires on individual question update and I suggest we don't add it by default to avoid storming app with partial updates on every single question. We have page changes and matrix questions, so this will be in pair with most of the form solutions out there.

While `onValueChanged` is great for analytics and understanding form lifecycle it's probably too "aggressive" of an update trigger for partial submission. Maybe we can enable with form configuration or even skip it for v1. Let me know

**Comment by dspetrov** [comment]
> @orilux , @dspetrov - looking at this task. The `onValueChanged` seems too frequent as it fires on individual question update and I suggest we don't add it by default to avoid storming app with partial updates on every single question. We have page changes and matrix questions, so this will be in pair with most of the form solutions out there.
> 
> While `onValueChanged` is great for analytics and understanding form lifecycle it's probably too "aggressive" of an update trigger for partial submission. Maybe we can enable with form configuration or even skip it for v1.
> 
> Vote with 👍 or 👎 to mark your preference

Before voting, I need some clarifications. If we don't utilize `onValueChanged`, then what happens with short one page forms - how are they going to be partially submitted?

**Comment by PeterMarinov** [comment]
Two scenarios:
1. No `onValueChanged` - then partial submit will occur on Matrix questions & Dynamic Panel added. 
2. WIth `onValueChanged` - then on every question for which the value changes, e.g. dropdown option changed, checkbox, radio button change...

I think maybe we add Partial submit for multiplace forms where users have at least clicked "Next" or we will have many abandoned surveys considered partials. We would want to have the "granular  `onValueChanged`" as an option imo and not needed for this initial iteration of the feature.

**Comment by dspetrov** [comment]
I think we better start with onValueChanged and see what we receive. In the beginning this won't crash our system or degrade the quality.
Having the data we will know better if we really have lots of abandoned submissions than if we ignore them.
Let's not add complications with different options. If there is a problem, it's easy to change this.

**Comment by dspetrov** [comment]
Another approach could be initiating the sending logic on all of the events as defined in the task but throttle for a period of time (configurable). Something like e.g.
- Send the partial submission on the first event and keep the timestamp
- On every next occurrence check if a period (e.g. 30 sec) passed
- When 30 sec have passed and an event happened, send again and update the timestamp
- Continue like this...

I think this almost doesn't add any complexity and challenges. However, we don't storm the API. The drawback is that we won't always have the latest data entered but we can play with the throttle period to lower it as much as possible but keeping the API not stormed.

**Comment by PeterMarinov** [comment]
Thanks for the input, @dspetrov. It seems easy to do and flexible, but I have one issue here:
doing the throttling is admitting that we fire the event way too often and that causes performance and business issue and I agree with your position from the first comment that we don't know that yet.

✅ With that said, I decided to stick to the original plan and fire on every `onValueChanged` until this is seen as source of issue.

Once we get there, we can implement tons of solutions like throttling, skipping event triggers and even computing form size (e.g. number of questions), which are considered "atomic", e.g. no partial submits apply.

I believe this follow the KISS principle and is more practical

**Comment by PeterMarinov** [comment]
Note this is in review. Have carved this item into another task to avoid blocking us - https://github.com/endatix/endatix/issues/267
