### ISSUE TITLE
Implement Hash service that can receive the Submission ID and return the Hash and validate the Hash

### ISSUE THREAD

**Issue by PeterMarinov** [endatix/endatix#239]
### Scope
- [x] Implement `IHashService` with two way hash algorithm to convert long to hash and vice versa. Use algorithm similar to YouTube shorts

### Acceptance Criteria
- `IHashService` can be injected via DI
- IHashService accepts generic param <T> as input and returns string for the Hash
-  Hash output resembles YouTube short Urls
- Decryption function accepts the string Hash and expected output <T> param 
- IHashService methods returns HashOperationResult, which has boolean flag for success and T or string params for the result. This way it can support the Result pattern and we can avoid exception based control flow

**Comment by dspetrov** [comment]
The solution is a bit different but achieves the same goals.
We have `ISubmissionTokenService` with methods `ObtainToken(long submissionId)` and `ResolveToken(string token)`. They do not encrypt/decrypt the ID but create/get a token for a submission ID or get the submission ID for a valid token.
