### ISSUE TITLE
API Project: Add support for CORS policy via AppSettings.json

### ISSUE THREAD

**Issue by dspetrov** [endatix/endatix#30]
**Original author:** @PeterMarinov 
**Original URL:** https://trello.com/c/VcY2iRKR/52-api-project-add-support-for-cors-policy-via-appsettingsjson

The web API has CORS disabled by default, which makes its usage via Web Browsers failing unless this is added in the Program.cs of the API project:
`app.UseCors(b => b.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod())`

### Problems
- Introduces security concerns as it allows requests from all origins, even untrusted ones
- Each change of CORS requires new code deployment and cannot be configured by environment

### Proposed Solution
- Refactor CORS to support whitelisting origins via AppSettings

Notes:
- https://learn.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-8.0
- Through API endpoints we can expose Microsoft settings
- Minimal effort - low hanging fruits

**Comment by PeterMarinov** [comment]
This is ready for review:
* PR is here - https://github.com/endatix/endatix/pull/87
* Documentation PR is here - https://github.com/endatix/docs-website/pull/6/files
