### ISSUE TITLE
Refactor Solution Architecture to allow using Endatix libraries as dotnet packages (no source code required)

### ISSUE THREAD

**Issue by dspetrov** [endatix/endatix#32]
**Original author:** @PeterMarinov 
**Original URL:** https://trello.com/c/9DlAFc41/56-refactor-solution-architecture-to-allow-using-endatix-libraries-as-dotnet-packages-no-source-code-required

## Goal
Based of this comment (https://bitbucket.org/orilux/surveysocket/pull-requests/22/diff#chg-src/SurveySocket.Api/Program.cs) it’s clear we want to allow using Endatix solution without the source code using packages and provide clear upgrade path in the future. Now Endatix.API project’s source is main Web host and has a lot of custom features and requirements implemented in it, which we need to change:

I think, the ideal solution will be to have a sample website, which is initialized from a vanilla one by adding all core dependencies, including:
- Endatix.API
- Endatix.Infrastructure
- Endatix.Core
- Endatix.SqlServer

It should be something like this as an architecture. This way we will have 3 distinct components:
- Core Endatix Dlls & Packages - not touched, unless upgraded to new version
- Custom Project Configs - configure features and settings of Endatix libs via configuration and Program.cs extension method in the Customer’s project
- Bespoke customer customizations - which extend core libraries via extensibility points, e.g. Plugins, DI and etc.

## Tasks

- [x] #52
- [x] #53
- [x] #54
- [x] #55
- [x] #56
- [x] #57
- [x] #70

## Diagram
![image](https://github.com/user-attachments/assets/d97fc7a1-eb4c-419e-ad57-7e1b07c57b94)

**Comment by PeterMarinov** [comment]
@dspetrov , @orilux  - marking this done. ✅ Closing
